### ISSUE TITLE
rework cli commands to use stats endpoint

### ISSUE THREAD

**Issue by monotasker** [MESH-Research/knowledge-commons-repository#291]

**Comment by cassandralem-msu** [comment]
Overall: stats endpoint is only good for stats on views and downloads. Makes getting these stats for a single deposit much easier, but not so useful for requesting stats about all deposits for example

**Comment by cassandralem-msu** [comment]
Following up on my previous comment: it may be necessary to just rely on the stats endpoint for numbers of views and downloads whether the user requests it for one deposit or all deposits, because it seems like the stats on views and downloads from the records endpoint is wrong (or at least there's a discrepancy between the records and stats endpoints). For example, for the deposit with id p1q3z-3a746, the records endpoint indicates that the number of views for the current version is 0, but the stats endpoint says 20. But I think there's a reasonable way to use the stats endpoint if the user requests stats for all the deposits.
